// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hirqqxleyjwqfigqqdgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcnFxeGxleWp3cWZpZ3FxZGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDMwMzUsImV4cCI6MjA2NjUxOTAzNX0.iwUvmDGCxO2jTRywmDOu4mi0-b4ZLw9UkWOf_DjypyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);